### ISSUE TITLE
[BUG] ssl.SSLCertVerificationError: certificate verify failed

### ISSUE THREAD

**Issue by MoSi8160** [python-bale-bot/python-bale-bot#54]
### what is your bale bot version?

2.4.8.1

### Reproduction Steps

code:
```
client = Bot(token=token)
....
...
client.run()
```

### Exception Result

```
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\request\http.py", line 129, in request
    async with self.__session.request(method=method, url=url, **kwargs) as response:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host tapi.bale.ai:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 1263, in main
    await self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 1255, in connect
    await self.get_bot()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 300, in get_bot
    response = await self.http.get_bot()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\request\http.py", line 156, in request
    raise NetworkError(str(error))
bale.error.NetworkError: Cannot connect to host tapi.bale.ai:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')]    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\bale\bale_bot.py", line 309, in <module>
    client.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 1267, in run
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 1262, in main
    async with self:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 113, in __aexit__
    await self.close()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 230, in close
    await self.updater.stop()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\updater.py", line 154, in stop
    raise RuntimeError("Updater is not running")
RuntimeError: Updater is not running
```

**Comment by kian-ahmadian** [comment]
Hi, @MoSi8160 
**This error is due to your lack of connection to Bale servers.**

**Comment by MoSi8160** [comment]
دستی با api کانکت میشه ولی با کد نمیتونه متصل بشه

**Comment by MoSi8160** [comment]
با requests میتونم به api خود بله وصل شم ولی با کتابخونه نمیشه

**Comment by MoSi8160** [comment]
ممنونم از شما. 

چطوری میتونم مشکل رو حل کنم ؟ 
توی اینترنت کلی سرچ کردم ولی هرکاری میکنم نمیشه

**Comment by kian-ahmadian** [comment]
عزیز کتابخانه و ما نوشتیم؛ به دنبال راه حال در اینترنت نباشید
در نسخه جدید این مشکل برطرف خواهد شد

**Comment by kian-ahmadian** [comment]
### The problem is fix on master branch. you must be wait for new version of library to fix that.

**Comment by MoSi8160** [comment]
سلام . حالتون خوب هست؟ نیاز من فوریه یه سرور خریدیم و می‌خوایم سریع راه اندازی کنیم ربات رو.
لطفاً بگید چطوری میتونیم اصلاح کنیم و استفاده کنیم از کتاب خانه؟

**Comment by kian-ahmadian** [comment]
سلام عزیز متشکرم
کتابخانه به زودی نسخه بعدی خودش و شاهد خواهد بود. این نسخه در هفته بعد رونمایی خواهد شد

**Comment by kian-ahmadian** [comment]
### **عزیز بهتون قولی نمیتونم بدم که در آینده شرمنده بشم؛ اما سعی میکنیم نسخه جدید و هر چه زودتر منتشر کنیم**

پیشنهاد میکنم نسخه لحظه رو، نصب و تست کنید تا با مطلع کردن ما از باگ های احتمالی اون ورژن بعدی و **بهتر** کنید 🔥

**Comment by MoSi8160** [comment]
چطوری نسخه لحظه رو نصب کنم؟

**Comment by MoSi8160** [comment]
کتاب خونه خیلی خوب و جامعی هست؛ خیلی لطف میکنید ممنونم از شما . من هر ربع ساعت سایت رو چک میکنم و منتظر نسخه جدیدتون هستم .
