### ISSUE TITLE
TypeError: ssl should be SSLContext, bool, Fingerprint or None, got {} instead.

### ISSUE THREAD

**Issue by MoSi8160** [python-bale-bot/python-bale-bot#55]
### what is your bale bot version?

2.4.8.1

### Reproduction Steps

سلام خسته نباشید. 

یک اروری رو قبلا گذارش داده بودمو شما درستش کردید . https://github.com/python-bale-bot/python-bale-bot/issues/54
کد من : 

```
client = Bot(token=token)
client.run()
```

### Exception Result

```
Traceback (most recent call last):
  File "d:\bale\bale_bot.py", line 309, in <module>
    client.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 1592, in run
    asyncio.run(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 1587, in main
    async with self:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 109, in __aenter__
    await self._setup_hook()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 106, in _setup_hook
    await self._http.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\request\http.py", line 104, in start
    self.__session = aiohttp.ClientSession(loop=self.loop, connector=aiohttp.TCPConnector(keepalive_timeout=20.0, **self._extra))
                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\connector.py", line 776, in __init__
    self._ssl = _merge_ssl_params(ssl, verify_ssl, ssl_context, fingerprint)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 192, in _merge_ssl_params
    raise TypeError(
TypeError: ssl should be SSLContext, bool, Fingerprint or None, got {} instead.
```

**Comment by MoSi8160** [comment]
`\bale\request\http.py` 
in line 80
i convert this line: `self._extra = dict(ssl=ssl)`
to this: `self._extra = dict(ssl=True)`

الان کد من راحت اجرا شده. تشکر از شما
