### ISSUE TITLE
bale.error.BaleError: [WinError 121] The semaphore timeout period has expired

### ISSUE THREAD

**Issue by MoSi8160** [python-bale-bot/python-bale-bot#56]
### what is your bale bot version?

2.4.8.1

### Reproduction Steps

when code started, after 1 minute, i got this err:

### Exception Result

```
[2023-11-11 15:13:46] [ERROR   ] bale.updater: Exception happened when polling for updates.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\request\http.py", line 136, in request
    async with self.__session.request(method=method, url=url, **kwargs) as response:
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client.py", line 560, in _request
    await resp.start(conn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 121] The semaphore timeout period has expired

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\updater.py", line 117, in _network_loop_retry
    if not await action_cb():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\updater.py", line 93, in action_getupdates
    raise exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\updater.py", line 91, in action_getupdates
    updates = await self.bot.get_updates(offset=self._last_offset)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\bot.py", line 1562, in get_updates
    response = await self._http.get_updates(params=handle_request_param(dict(offset=offset, limit=limit)))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\bale\request\http.py", line 166, in request
    raise BaleError(str(error))
bale.error.BaleError: [WinError 121] The semaphore timeout period has expired
```

**Comment by kian-ahmadian** [comment]
وقت بخیر عزیز، این مشکل به دلیل تایم اوت خوردن در اتصال به اینترنت پیش اومده، **با این حال تغییراتی اعمال میدیم که راحت تر با کانکتور مربوط به کتابخانه اتصال ارتباط برقرار کنید**
