### ISSUE TITLE
موقف شدن بات بعد از چند روز !

### ISSUE THREAD

**Issue by sadraatrian** [python-bale-bot/python-bale-bot#81]
### what is your bale bot version?

last version

### Reproduction Steps

سلام 
نمیدونم چرا ولی بعد از اجرا کردن بات روی هاست cpanel توسط دستور screen یا nohup بعد از چند روز اف میشه و دوباره باید برم توی هاست و اجرا کنم ! نمیدونمم چرا ولی این مشکل از همون اول بود .
نسخه پایتون هم 3.8 و خود کتابخانه هم نسخه آخره 

### Exception Result

و توی log ها هم همون ارور های همیشگی را میده :
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/updater.py", line 120, in _network_loop_retry
    if not await action_cb():
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/updater.py", line 96, in action_getupdates
    raise exc
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/updater.py", line 94, in action_getupdates
    updates = await self.bot.get_updates(offset=self._last_offset)
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/bot.py", line 1250, in get_updates
    response = await self.http.get_updates(offset, limit)
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/request/http.py", line 162, in request
    raise HTTPException(error)
bale.error.HTTPException: None: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

[2024-02-03 23:39:10] [ERROR   ] bale.updater: Exception happened when polling for updates.
Traceback (most recent call last):
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/request/http.py", line 152, in request
    raise APIError(
bale.error.APIError: None: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/updater.py", line 120, in _network_loop_retry
    if not await action_cb():
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/updater.py", line 96, in action_getupdates
    raise exc
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/updater.py", line 94, in action_getupdates
    updates = await self.bot.get_updates(offset=self._last_offset)
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/bot.py", line 1250, in get_updates
    response = await self.http.get_updates(offset, limit)
  File "/home/balebott/virtualenv/project/3.8/lib/python3.8/site-packages/bale/request/http.py", line 162, in request
    raise HTTPException(error)
bale.error.HTTPException: None: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

شما میدونید باید چه کار کنم ؟!

**Comment by kian-ahmadian** [comment]
سلام عزیز وقت بخیر
**این ارور از طرف سرور های بله برای شما ارسال شده. متأسفانه چاره ای هم نیست و مجبوریم هندلر هایی برای کنترل این موضوع قرار دهیم**

به زودی و پس از بررسی های بیشتر در خصوص اقدامات لازمه آگاهتون میکنیم 🙏

**Comment by imanjahanyan** [comment]
> سلام عزیز وقت بخیر **این ارور از طرف سرور های بله برای شما ارسال شده. متأسفانه چاره ای هم نیست و مجبوریم هندلر هایی برای کنترل این موضوع قرار دهیم**
> 
> به زودی و پس از بررسی های بیشتر در خصوص اقدامات لازمه آگاهتون میکنیم 🙏

سلام، وقت بخیر
یه راه حل موقتی و غیر متعارف هست، میشه به صورت زیر فعلا استفاده کرد:
while True:
    try:
        client.run()
     except:
         pass

**Comment by kian-ahmadian** [comment]
بله عزیز این راه حل هم وجود داره؛ اما در نسخه جدیدی که به زودی منتشر میکنیم هندلر هایی برای پیگیری این موضوع پیاده شده اند
